@XPTO.Presentation.API_HostAddress = https://localhost:7274


##POST COM ENDERECO

POST {{XPTO.Presentation.API_HostAddress}}/Clientes
Content-Type: application/json
  {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "nome": "string",
    "email": "string@outlook.com",
    "telefone": "string",
    "endereco": {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "rua": "string",
      "numero": "string",
      "cidade": "string",
      "estado": "RJ",
      "cep": "26220-999"
    }
  }

###

##POST SEM ENDERECO
POST {{XPTO.Presentation.API_HostAddress}}/Clientes
Content-Type: application/json
{
    "nome": "Endereco Nulo",
    "email": "string@gmail",
    "telefone": "string",
    "endereco": null
}

###endregion


